
version: '3.3'
services:
  app:
    image: sganes/todoapp
    container_name: app
    ports: 
      - 8080:80
    environment:
      - MONGO_URI=mongodb://mongo:27017
    links: 
      - mongo
  mongo:
    image: mongo:3.0.15
    container_name: mongo
    ports: 
      - 27017:27017
    volumes:
      - /data./data/db  